name: css-project
channels:
  - conda-forge
dependencies:
  - python=3.10
  - anaconda
  - numpy
  - scipy
  - ipykernel
  - networkx
  - matplotlib
  - seaborn
  - numba
  - pip
  - pip:
    - cellpylib